@startuml

package domain.game {
    +class Card {
        -cardType: CardType
        -isMarked: boolean
        -isFacedUp: boolean

        +Card(cardType: CardType): Card
        +getCardType(): CardType
        +checkIfMarked(): boolean
        +setFacedUp(): void
        +checkIfFacedUp(): boolean
    }

    enum CardType {
    }

    class Deck {
    }

    class Game {
    }

    enum GameType {
    }

    class Instantiator {
    }

    class Player {
    }
}

package ui {
    class GameUI {
    }

    class Main {
    }
}

'QUESTIONS:
'-how to best represent the resource bundle? package? class?
'-out of curiosity, are tests ever part of a design diagram?

@enduml